package Basic;

import java.io.IOException;
import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

public class Contacts 
{
	public static void main(String[] args) throws InterruptedException, IOException 
	{
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));
		driver.get("https://demo.vtiger.com/vtigercrm/");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[text()='Sign in']")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("appnavigator")).click();
		Thread.sleep(2000);
		WebElement ele = driver.findElement(By.xpath("//span[text()=' MARKETING']"));
		Actions a= new Actions(driver);
		a.moveToElement(ele);
		a.perform();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//span[text()=' Contacts'])[1]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_listView_basicAction_LBL_ADD_RECORD")).click();
		Thread.sleep(2000);
		WebElement ele1 = driver.findElement(By.name("salutationtype"));
		Select s= new Select(ele1);
		s.selectByValue("Mr.");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_firstname")).sendKeys("Aatish");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_lastname")).sendKeys("Dhawale");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_phone")).sendKeys("7774845763");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_account_id_create")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("Accounts_editView_fieldName_accountname")).sendKeys("Nestle");
		Thread.sleep(2000);
		driver.findElement(By.id("Accounts_editView_fieldName_website")).sendKeys("www.google.com");
		Thread.sleep(2000);
		driver.findElement(By.id("Accounts_editView_fieldName_phone")).sendKeys("7774845763");
		Thread.sleep(2000);
		WebElement ele2 = driver.findElement(By.xpath("(//select[@name='assigned_user_id'])[2]"));
		Select s1= new Select(ele2);
		s1.selectByValue("3");
		driver.findElement(By.xpath("//button[@class='btn btn-success']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[text()='Yes']")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_mobile")).sendKeys("7774845763");
		WebElement ele3 = driver.findElement(By.xpath("//select[@name='leadsource']"));
		Select s2= new Select(ele3);
		s2.selectByValue("Employee");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_homephone")).sendKeys("123456789");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_title")).sendKeys("Contacts");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_otherphone")).sendKeys("8008000");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_department")).sendKeys("contact");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_fax")).sendKeys("xyz");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_email")).sendKeys("mitali464@gmail.com");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_birthday")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//td[text()='11']")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_assistant")).sendKeys("abc");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_contact_id_create")).click();
		Thread.sleep(2000);
		WebElement ele4 = driver.findElement(By.xpath("(//select[@name='salutationtype'])[2]"));
		Select s4=new Select(ele4);
		s4.selectByVisibleText("Ms.");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@name='firstname'])[2]")).sendKeys("abc");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@name='lastname'])[2]")).sendKeys("vvvv");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@name='phone'])[2]")).sendKeys("123456789");
		Thread.sleep(2000);
	   // driver.findElement(By.xpath("(//i[@id='Contacts_editView_fieldName_account_id_select'])[2]")).click();
		//driver.findElement(By.linkText("Capgemini")).click();
//		Thread.sleep(2000);
//		driver.findElement(By.xpath("//button[text()='Yes']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@name='email'])[2]")).sendKeys("sgapat@gmail.com");
		Thread.sleep(2000);
		WebElement ele5 = driver.findElement(By.xpath("(//select[@name='assigned_user_id'])[2]"));
		Select s5=new Select(ele5);
		s5.selectByValue("3");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//strong[text()='Save']")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_assistantphone")).sendKeys("964534210");
		Thread.sleep(2000);
		JavascriptExecutor js= (JavascriptExecutor)driver;
		js.executeScript("window.scrollBy(0,100)");

		driver.findElement(By.id("Contacts_editView_fieldName_secondaryemail")).sendKeys("abcd@gmail.com");
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@name='emailoptout'])[2]")).click();
		Thread.sleep(2000);
		JavascriptExecutor jse= (JavascriptExecutor)driver;
		jse.executeScript("window.scrollBy(0,200)");

		driver.findElement(By.xpath("(//input[@data-fieldtype='checkbox'])[2]")).click();
		
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@name='reference'])[2]")).click();
		WebElement ele6 = driver.findElement(By.xpath("//select[@type='owner']"));
		Select s6= new Select(ele6);
		s6.selectByValue("3");
		Thread.sleep(2000);
		JavascriptExecutor jse1= (JavascriptExecutor)driver;
		jse1.executeScript("window.scrollBy(0,400)");

		driver.findElement(By.xpath("(//input[@name='notify_owner'])[2]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//input[@name='portal'])[2]")).click();
		Thread.sleep(2000);
		//driver.findElement(By.id("Contacts_editView_fieldName_support_start_date")).sendKeys("22-05-2023");
		Thread.sleep(2000);
		JavascriptExecutor jse2= (JavascriptExecutor)driver;
		jse2.executeScript("window.scrollBy(0,400)");

		driver.findElement(By.name("mailingstreet")).sendKeys("pune");
		Thread.sleep(2000);
		driver.findElement(By.name("otherstreet")).sendKeys("katraj");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_mailingpobox")).sendKeys("abc");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_otherpobox")).sendKeys("adc");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_mailingcity")).sendKeys("pune");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_othercity")).sendKeys("nanded");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_mailingstate")).sendKeys("maharashtra");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_otherstate")).sendKeys("maharashtra");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_mailingzip")).sendKeys("431605");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_otherzip")).sendKeys("431605");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_mailingcountry")).sendKeys("India");
		Thread.sleep(2000);
		driver.findElement(By.id("Contacts_editView_fieldName_othercountry")).sendKeys("India");
		Thread.sleep(2000);
		JavascriptExecutor jse3= (JavascriptExecutor)driver;
		jse3.executeScript("window.scrollBy(0,400)");

		driver.findElement(By.name("description")).sendKeys("Filled detail.");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class='fileUploadBtn btn btn-primary']")).click();
		Thread.sleep(2000);
		Runtime.getRuntime().exec("C:\\Users\\adhaw\\OneDrive\\Desktop\\File.exe");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[text()='Save']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//li[@class='dropdown']")).click();
		Thread.sleep(2000);
		driver.findElement(By.linkText("Sign Out")).click();
	}

}
